# Generated by Django 3.2.5 on 2021-07-30 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('e_name', models.CharField(db_column='客户姓名', max_length=64)),
                ('e_age', models.IntegerField(db_column='客户年龄')),
                ('e_job', models.CharField(blank=True, db_column='客户职业', max_length=64, null=True)),
                ('province', models.CharField(blank=True, db_column='客户所在省', max_length=32, null=True)),
                ('city', models.CharField(blank=True, db_column='客户所在市', max_length=32, null=True)),
                ('p_name', models.CharField(db_column='项目名称', max_length=64)),
                ('join_time', models.DateTimeField(db_column='加入项目时间')),
                ('update_time', models.DateTimeField(db_column='最近更新时间')),
                ('is_delete', models.BooleanField(db_column='是否删除', default=False)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='ProjectsList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(db_column='项目名称', max_length=64)),
                ('p_start_time', models.DateTimeField(db_column='项目开始时间')),
                ('p_end_time', models.DateTimeField(db_column='项目结束时间')),
                ('employee_num', models.IntegerField(db_column='项目人数', default=0)),
                ('user_id', models.IntegerField(db_column='所属管理员')),
                ('is_delete', models.BooleanField(db_column='是否删除', default=False)),
            ],
            options={
                'db_table': 'project_list',
            },
        ),
        migrations.CreateModel(
            name='ProjectsDetails',
            fields=[
                ('pd_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(db_column='项目名称', max_length=64)),
                ('p_introduce', models.CharField(db_column='项目介绍', max_length=255)),
                ('e_name', models.CharField(db_column='客户姓名', max_length=32)),
                ('e_age', models.IntegerField(db_column='客户年龄')),
                ('id', models.ForeignKey(db_column='项目详情 ID', on_delete=django.db.models.deletion.CASCADE, to='BackApi.projectslist')),
            ],
            options={
                'db_table': 'project_details',
            },
        ),
    ]
