# Generated by Django 3.2.5 on 2021-08-09 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('e_name', models.CharField(max_length=64)),
                ('e_age', models.IntegerField(blank=True, null=True)),
                ('e_job', models.CharField(blank=True, max_length=64, null=True)),
                ('province', models.CharField(blank=True, max_length=32, null=True)),
                ('city', models.CharField(blank=True, max_length=32, null=True)),
                ('p_name', models.CharField(blank=True, max_length=64, null=True)),
                ('join_time', models.DateTimeField(auto_now=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_in_project', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='ProjectsList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(blank=True, max_length=64, null=True)),
                ('p_start_time', models.DateField(blank=True, null=True)),
                ('p_end_time', models.DateField(blank=True, null=True)),
                ('employee_num', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'project_list',
            },
        ),
        migrations.CreateModel(
            name='ProjectsDetails',
            fields=[
                ('pd_id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(blank=True, max_length=64, null=True)),
                ('p_introduce', models.CharField(blank=True, max_length=255, null=True)),
                ('e_name', models.CharField(blank=True, max_length=32, null=True)),
                ('e_age', models.IntegerField(blank=True, null=True)),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackApi.employee')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackApi.projectslist')),
            ],
            options={
                'db_table': 'project_details',
            },
        ),
    ]
